FROM ubuntu:16.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install --yes \
    ca-certificates \
    g++ \
    gcc \
    git-core \
    make \
    python3 \
    qtdeclarative5-dev
